nodeLinker: node-modules

npmPublishRegistry: "https://npm.chevs.fun/"

npmScopes:
  limbus:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_CHEVS_FUN_AUTH_TOKEN}"
    npmPublishRegistry: "https://npm.chevs.fun/"
    npmRegistryServer: "https://npm.chevs.fun/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.0.2.cjs
